project:
  type: website
  output-dir: docs

website:
  title: "FylloClip tutorial"
  navbar:
    logo: images/logo_laimburg.png  # Hier wird das Logo eingefügt
    href: https://www.laimburg.it       # Ziel-Link
    
    left:
      - href: content/index.qmd
        text: Home
    tools:
      - icon: github
        href: https://github.com/


  sidebar:
    style: "docked"
    search: true
    contents:
      - section: " "
        contents:
          - content/legal_note.qmd
      - section: "**HARDWARE**"
        contents:
          - content/PCBs.qmd
          - content/list_of_components.qmd
          - content/burning_bootloader.qmd
      - section: "**ASSEMBLY**"
        contents:
          - content/assembly_instructions.qmd
      - section: "**SOFTWARE**"
        contents:
          - content/code_for_arduino.qmd
          - content/device_registration.qmd
          - content/cloud.qmd
      - section: "**DEPLOYING THE DEVICE**"
        contents:
          - content/testing_the_device.qmd
          - content/attaching_the_sensor.qmd
          - content/data_interpretation.qmd
    
      

format:
  html:
    theme: flatly
  #  mainfont: arial
  #  fontsize: 1.5rem
  #  fontcolor: "#0013d5"
    linkcolor: "blue"
  #  monofont: courier new
    css: styles.css
    toc: true

editor: visual